[tools]
lefthook = "2.1.0"
cocogitto = "6.5.0"
act = "0.2.84"
python = "3.14.3"
uv = "0.10.1"
ruff = "0.15.0"
"pipx:pyrefly" = "0.57.1"

[tasks.setup]
run = "lefthook install"

[tasks.format]
run = "ruff format ."

[tasks.lint]
run = "ruff check ."

[tasks.typecheck]
run = 'pyrefly check'

[tasks.act]
run = 'act pull_request --secret-file .env -e .github/act/pull_request.json -j checks'
